services:
    phlexible_media_manager.file_meta_set_resolver:
        class: Phlexible\Component\MediaManager\Meta\FileMetaSetResolver
        arguments:
            - "@phlexible_meta_set.meta_set_manager"

    phlexible_media_manager.folder_meta_set_resolver:
        class: Phlexible\Component\MediaManager\Meta\FolderMetaSetResolver
        arguments:
            - "@phlexible_meta_set.meta_set_manager"

    phlexible_media_manager.doctrine.file_meta_data_manager:
        class: Phlexible\Component\MediaManager\Meta\FileMetaDataManager
        arguments:
            - "@phlexible_meta_set.meta_set_manager"
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - "@logger"

    phlexible_media_manager.doctrine.folder_meta_data_manager:
        class: Phlexible\Component\MediaManager\Meta\FolderMetaDataManager
        arguments:
            - "@phlexible_meta_set.meta_set_manager"
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - "@logger"
